name: Flutter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Tests
        run: flutter test --no-pub --coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: "./coverage/lcov.info"
          min_coverage: 95
